name: JFrog XRay Audit

# Use JFrog XRay to 'audit' the source files in the solution.
# This reusable workflow assumes that the workspace was persisted into an artifact.

permissions:
  contents: read
  id-token: write
  packages: read

on:

  workflow_call:

    inputs:

      jfrog_api_base_url:
        description: 'JFrog platform url (for example: https://rimdev.jfrog.io)'
        required: true
        type: string

      jfrog_xray_watch_list:
        description: Comma-delimited list (with no spaces) of XRay watches to enforce.  Passed to "jf audit" via the "--watches" argument.
        required: true
        type: string

      persisted_workspace_artifact_name:
        description: Name of the artifact which contains the persisted workspace directory.
        required: false
        type: string
        default:

      project_directory:
        description: Location of the solution file for the dotnet solution.  Defaults to the root directory.
        required: false
        type: string
        default: ./

      report_artifact_name:
        description: The GitHub artifact name for the report file.
        required: true
        type: string

      report_artifact_retention_days:
        required: false
        type: number
        default: 90

    secrets:

      jfrog_api_key:
        description: The secret API key needed in order to access the JFrog XRay API.
        required: true

    outputs:
      report_artifact_name:
        value: ${{ jobs.xray-scan.outputs.report_artifact_name }}

jobs:

  xray-audit:
    name: JFrog XRay Audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project_directory }}

    outputs:
      report_artifact_name: ${{ env.REPORTARTIFACTNAME }}

    env:
      CI: true
      NUGETHASHFILES: "${{ inputs.project_directory }}**/*.csproj"
      PROJECTDIRECTORY: ${{ inputs.project_directory }}
      REPORTARTIFACTNAME: ${{ inputs.report_artifact_name }}
      XRAYWATCHES: ${{ inputs.jfrog_xray_watch_list }}

    steps:

      - name: Validate secrets.jfrog_api_key
        uses: ritterim/public-github-actions/actions/regex-validator@v1.10.0
        with:
          regex_pattern: '^[A-Za-z0-9-_]*\.[A-Za-z0-9-_]*\.[A-Za-z0-9-_]*$'
          value: ${{ secrets.jfrog_api_key }}

      - name: Validate inputs.project_directory
        uses: ritterim/public-github-actions/actions/path-name-validator@v1.10.0
        with:
          path_name: ${{ env.PROJECTDIRECTORY }}

      - name: Validate inputs.report_artifact_name
        uses: ritterim/public-github-actions/actions/file-name-validator@v1.10.0
        with:
          file_name: ${{ env.REPORTARTIFACTNAME }}

      - name: Restore Workspace
        uses: ritterim/public-github-actions/forks/persist-workspace@v1.10.0
        with:
          action: retrieve
          artifact_name: ${{ inputs.persisted_workspace_artifact_name }}

      - name: Setup ~/.nuget/packages cache
        uses: actions/cache@v3
        with:
          key: nuget-packages-${{ runner.os }}-${{ hashFiles(env.NUGETHASHFILES) }}
          path: |
            ~/.nuget/packages

      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ inputs.jfrog_api_base_url }}
          JF_ACCESS_TOKEN: ${{ secrets.jfrog_api_key }}

      # Note: The 'ping' can succeed even if the API key (JF_ACCESS_TOKEN) is wrong/missing.
      - name: Check JFrog CLI version and server connection.
        run: |
          jf --version
          jf rt ping

      - name: jf audit
        id: audit
        run: |
          set -o pipefail
          jf audit --watches="${XRAYWATCHES}" | tee "${REPORTARTIFACTNAME}.txt"
        continue-on-error: true

      - name: Report File
        run: cat "${REPORTARTIFACTNAME}.txt"

      - name: Upload Artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPORTARTIFACTNAME }}
          path: ${{ env.REPORTARTIFACTNAME }}.*
          retention-days: ${{ inputs.report_artifact_retention_days }}
          if-no-files-found: error

      - name: Fail build on audit error
        if: steps.audit.outcome == 'failure'
        run: exit 1
