name: NPM PR Build-Test

# Designed to be called when a PR is opened against a branch in the repository.  This operates with a read-only GitHub Token for safety.

permissions:
  contents: read
  packages: read

on:

  workflow_call:

    inputs:

      node_version:
        required: false
        type: string
        default: '18.x'

      package_json_filename:
        description: Name of the 'package.json' file if not the default name.
        required: false
        type: string
        default: package.json

      project_directory:
        description: Location of the package.json file for the NPM package.
        required: false
        type: string
        default: ./

      run_tests:
        required: false
        type: boolean
        default: true

jobs:

  npm-build:
    uses: ritterim/public-github-actions/.github/workflows/npm-build.yml@v1.5.0
    #uses: ./.github/workflows/npm-build.yml
    with:
      node_version: ${{ inputs.node_version }}
      package_json_filename: ${{ inputs.package_json_filename }}
      project_directory: ${{ inputs.project_directory }}

  npm-test:
    uses: ritterim/public-github-actions/.github/workflows/npm-test.yml@v1.5.0
    #uses: ./.github/workflows/npm-test.yml
    needs: [ npm-build ]
    with:
      persisted_workspace_artifact_name: ${{ needs.npm-build.outputs.persisted_workspace_artifact_name }}
      project_directory: ${{ needs.npm-build.outputs.project_directory }}
      run_tests: ${{ inputs.run_tests }}
